version: '3.3'

services:
  db:
    image: postgres:14
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appointments_db
    volumes:
      - ./db_data:/var/lib/postgresql/data